apiVersion: v1
kind: Service
metadata:
  name: fastapi-test-service
spec:
  selector:
    app: fastapi-delay-predictor
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-delay-predictor
spec:
  selector:
    matchLabels:
      app: fastapi-delay-predictor
  replicas: 10
  template:
    metadata:
      labels:
        app: fastapi-delay-predictor
    spec:
      containers:
        - name: fastapi-delay-predictor
          image: fastapi-delay-predictor
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000